version: '3.8'

services:
  laravel-docker:
    container_name: laravel-doc-app
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
     - 9000:80
    volumes:
     - ./larave-app:/var/www/html
